14-11-2024 11:01:41 - INFO - Engine created - initialize - 43
14-11-2024 11:02:04 - INFO - Login Successful. Welcome aditya - user_login - 49
14-11-2024 11:02:07 - INFO - Session closed - get_session - 77
14-11-2024 11:02:07 - INFO - Exitting ...... - <module> - 80
14-11-2024 11:02:07 - INFO - Logout Successful. Bye aditya - user_logout - 74
14-11-2024 11:02:07 - INFO - Connection closed - disconnect - 90
14-11-2024 11:22:16 - INFO - Engine created - initialize - 43
14-11-2024 11:22:21 - ERROR - Login Error: test - user_login - 61
Traceback (most recent call last):
  File "/home/aditya/test/orm/controller/user/User.py", line 58, in user_login
    raise Exception("test")
Exception: test
14-11-2024 11:22:50 - INFO - Session closed - get_session - 77
14-11-2024 11:22:50 - INFO - Exitting ...... - <module> - 80
14-11-2024 11:22:50 - INFO - Connection closed - disconnect - 90
14-11-2024 11:22:51 - INFO - Engine created - initialize - 43
14-11-2024 11:22:55 - ERROR - Login Error - user_login - 61
Traceback (most recent call last):
  File "/home/aditya/test/orm/controller/user/User.py", line 58, in user_login
    raise Exception("test")
Exception: test
14-11-2024 11:23:12 - INFO - Session closed - get_session - 77
14-11-2024 11:23:12 - INFO - Exitting ...... - <module> - 80
14-11-2024 11:23:12 - INFO - Connection closed - disconnect - 90
14-11-2024 11:23:43 - INFO - Engine created - initialize - 43
14-11-2024 11:23:48 - ERROR - Login Error - user_login - 59
Traceback (most recent call last):
  File "/home/aditya/test/orm/controller/user/User.py", line 43, in user_login
    user_id, user_password, a = res
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)
14-11-2024 11:23:53 - INFO - Session closed - get_session - 77
14-11-2024 11:23:53 - INFO - Exitting ...... - <module> - 80
14-11-2024 11:23:53 - INFO - Connection closed - disconnect - 90
14-11-2024 12:04:47 - INFO - Engine created - initialize - 43
14-11-2024 12:04:50 - INFO - Session closed - _get_session - 75
14-11-2024 12:04:50 - INFO - Login Successful. Welcome aditya - user_login - 57
14-11-2024 12:04:56 - WARNING - ====Cache miss==== - get - 46
14-11-2024 12:04:56 - INFO - Session closed - _get_session - 75
14-11-2024 12:04:56 - ERROR - Query results mismatch. Can't zip - get_user_data - 145
14-11-2024 12:09:09 - INFO - Logout Successful. Bye aditya - user_logout - 75
14-11-2024 12:09:09 - INFO - Connection closed - disconnect - 108
14-11-2024 12:09:11 - INFO - Engine created - initialize - 43
14-11-2024 12:09:17 - INFO - Session closed - _get_session - 75
14-11-2024 12:09:17 - ERROR - This username or email already exists - user_signup - 98
14-11-2024 12:10:22 - INFO - Session closed - _get_session - 75
14-11-2024 12:10:22 - INFO - Session closed - _get_session - 75
14-11-2024 12:10:22 - ERROR - Query execution error - execute_query - 94
Traceback (most recent call last):
  File "/home/aditya/test/orm/connection/Connection.py", line 85, in execute_query
    res = session.execute(query).all()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/miniconda3/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 1379, in all
    return self._allrows()
           ^^^^^^^^^^^^^^^
  File "/home/aditya/miniconda3/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 546, in _allrows
    make_row = self._row_getter
               ^^^^^^^^^^^^^^^^
  File "/home/aditya/miniconda3/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 1253, in __get__
    obj.__dict__[self.__name__] = result = self.fget(obj)
                                           ^^^^^^^^^^^^^^
  File "/home/aditya/miniconda3/lib/python3.12/site-packages/sqlalchemy/engine/result.py", line 471, in _row_getter
    key_to_index = metadata._key_to_index
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/miniconda3/lib/python3.12/site-packages/sqlalchemy/engine/cursor.py", line 1361, in _key_to_index
    self._we_dont_return_rows()
  File "/home/aditya/miniconda3/lib/python3.12/site-packages/sqlalchemy/engine/cursor.py", line 1341, in _we_dont_return_rows
    raise exc.ResourceClosedError(
sqlalchemy.exc.ResourceClosedError: This result object does not return rows. It has been closed automatically.
14-11-2024 12:10:22 - INFO - Welcome dkfj. Signup successful - user_signup - 105
14-11-2024 12:11:08 - INFO - Exitting ...... - <module> - 82
14-11-2024 12:11:08 - INFO - Connection closed - disconnect - 108
14-11-2024 14:07:12 - INFO - Engine created - __init__ - 33
14-11-2024 14:07:17 - INFO - Session closed - _get_session - 65
14-11-2024 14:07:17 - ERROR - Wrong username or password - user_login - 42
14-11-2024 14:07:22 - INFO - Session closed - _get_session - 65
14-11-2024 14:07:22 - INFO - Login Successful. Welcome aditya - user_login - 36
14-11-2024 14:07:25 - ERROR - Oops Something went wrong! - <module> - 83
Traceback (most recent call last):
  File "/home/aditya/test/orm/main.py", line 35, in <module>
    user.user_logout()
  File "/home/aditya/test/orm/controller/user/User.py", line 54, in user_logout
    self.disconnect_db()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'disconnect_db'
14-11-2024 14:09:22 - INFO - Engine created - initialize - 44
14-11-2024 14:09:27 - ERROR - Login Error: 'NoneType' object has no attribute 'execute_query' - user_login - 46
Traceback (most recent call last):
  File "/home/aditya/test/orm/controller/user/User.py", line 27, in user_login
    res = db_connection.execute_query(query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'execute_query'
14-11-2024 14:09:32 - INFO - Exitting ...... - <module> - 80
14-11-2024 14:15:01 - INFO - Engine created - initialize - 44
14-11-2024 14:15:02 - ERROR - Invalid task: lgin - <module> - 75
14-11-2024 14:15:06 - INFO - Session closed - _get_session - 76
14-11-2024 14:15:06 - INFO - Login Successful. Welcome aditya - user_login - 36
14-11-2024 14:15:11 - ERROR - Invalid task: logou - <module> - 75
14-11-2024 14:15:14 - ERROR - Oops Something went wrong! - <module> - 83
Traceback (most recent call last):
  File "/home/aditya/test/orm/main.py", line 35, in <module>
    user.user_logout()
  File "/home/aditya/test/orm/controller/user/User.py", line 54, in user_logout
    self.disconnect_db()
    ^^^^^^^^^^^^^^^^^^
AttributeError: 'User' object has no attribute 'disconnect_db'
14-11-2024 14:15:31 - INFO - Engine created - initialize - 44
14-11-2024 14:15:35 - INFO - Session closed - _get_session - 76
14-11-2024 14:15:35 - INFO - Login Successful. Welcome aditya - user_login - 36
14-11-2024 14:15:37 - INFO - Exitting ...... - <module> - 80
14-11-2024 14:20:32 - INFO - Engine created - initialize - 43
14-11-2024 14:20:36 - INFO - Session closed - _get_session - 75
14-11-2024 14:20:36 - INFO - Login Successful. Welcome aditya - user_login - 36
14-11-2024 14:20:39 - INFO - Logout Successful. Bye aditya - user_logout - 54
14-11-2024 14:45:44 - INFO - Engine created - initialize - 42
14-11-2024 14:45:48 - INFO - Session closed - _get_session - 74
14-11-2024 14:45:48 - INFO - Login Successful. Welcome aditya - user_login - 34
14-11-2024 14:45:50 - WARNING - ====Cache miss==== - get - 87
14-11-2024 14:45:50 - INFO - Session closed - _get_session - 74
14-11-2024 14:45:56 - INFO - ====Cache hit==== - get - 90
14-11-2024 14:46:00 - INFO - ====Cache hit==== - get - 90
14-11-2024 14:46:09 - INFO - ====Cache hit==== - get - 90
14-11-2024 14:46:12 - INFO - Connection closed - disconnect - 107
14-11-2024 14:46:12 - INFO - Logout Successful. Bye aditya - user_logout - 55
14-11-2024 14:47:39 - INFO - Engine created - initialize - 42
14-11-2024 14:47:41 - ERROR - Invalid task: logn - <module> - 66
14-11-2024 14:47:45 - INFO - Session closed - _get_session - 74
14-11-2024 14:47:45 - INFO - Login Successful. Welcome aditya - user_login - 34
14-11-2024 14:47:45 - INFO - Connection closed - disconnect - 107
14-11-2024 14:47:53 - INFO - ====Cache hit==== - get - 90
14-11-2024 14:47:53 - INFO - Redis connection closed - disconnect - 42
14-11-2024 14:47:59 - INFO - Exitting ...... - <module> - 71
14-11-2024 14:47:59 - INFO - Logout Successful. Bye aditya - user_logout - 58
14-11-2024 14:53:17 - INFO - Engine created - initialize - 42
14-11-2024 14:53:20 - INFO - Session closed - _get_session - 74
14-11-2024 14:53:20 - INFO - Login Successful. Welcome aditya - user_login - 33
14-11-2024 14:53:29 - WARNING - Some user is already logged in - user_login - 17
14-11-2024 14:53:38 - WARNING - ====Cache miss==== - get - 87
14-11-2024 14:53:38 - INFO - Session closed - _get_session - 74
14-11-2024 14:53:38 - INFO - Redis connection closed - disconnect - 42
14-11-2024 14:53:42 - INFO - ====Cache hit==== - get - 90
14-11-2024 14:53:42 - INFO - Redis connection closed - disconnect - 42
14-11-2024 14:53:51 - INFO - Exitting ...... - <module> - 65
14-11-2024 14:53:51 - INFO - Connection closed - disconnect - 107
14-11-2024 14:53:51 - INFO - Logout Successful. Bye aditya - user_logout - 55
14-11-2024 14:59:17 - INFO - Engine created - initialize - 41
14-11-2024 14:59:20 - INFO - Session closed - _get_session - 73
14-11-2024 14:59:20 - INFO - Login Successful. Welcome aditya - user_login - 33
14-11-2024 14:59:28 - INFO - Exitting ...... - <module> - 22
14-11-2024 14:59:28 - INFO - Connection closed - disconnect - 106
14-11-2024 14:59:28 - INFO - Logout Successful. Bye aditya - user_logout - 55
14-11-2024 15:05:55 - INFO - Engine created - initialize - 41
14-11-2024 15:06:06 - ERROR - Invalid email - <module> - 47
14-11-2024 15:06:07 - INFO - Exitting ...... - <module> - 60
14-11-2024 15:06:07 - INFO - Connection closed - disconnect - 106
14-11-2024 15:16:35 - INFO - Engine created - initialize - 41
14-11-2024 15:16:38 - ERROR - Login Error: 'MySqlConnection' object has no attribute '_check_initialized' - user_login - 43
Traceback (most recent call last):
  File "/home/aditya/test/orm/controller/user/User.py", line 24, in user_login
    res = db_connection.execute_query(query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aditya/test/orm/connection/MySqlConnection.py", line 79, in execute_query
    self._check_initialized()
    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MySqlConnection' object has no attribute '_check_initialized'
14-11-2024 15:16:42 - INFO - Exitting ...... - <module> - 60
14-11-2024 15:16:42 - INFO - Connection closed - disconnect - 106
14-11-2024 15:16:48 - INFO - Engine created - initialize - 41
14-11-2024 15:16:52 - INFO - Session closed - _get_session - 73
14-11-2024 15:16:52 - INFO - Login Successful. Welcome aditya - user_login - 33
14-11-2024 15:16:55 - INFO - Connection closed - disconnect - 106
14-11-2024 15:16:55 - INFO - Logout Successful. Bye aditya - user_logout - 55
14-11-2024 15:19:01 - INFO - Engine created - __init__ - 41
14-11-2024 15:19:04 - INFO - Session closed - _get_session - 73
14-11-2024 15:19:04 - ERROR - Wrong username or password - user_login - 39
14-11-2024 15:19:06 - INFO - Exitting ...... - <module> - 60
14-11-2024 15:19:06 - INFO - Connection closed - disconnect - 106
14-11-2024 15:20:27 - INFO - Engine created - __init__ - 41
14-11-2024 15:20:37 - INFO - Engine created - __init__ - 41
14-11-2024 15:20:44 - INFO - Exitting ...... - <module> - 60
14-11-2024 15:20:44 - INFO - Connection closed - disconnect - 106
14-11-2024 15:20:45 - INFO - Engine created - __init__ - 41
14-11-2024 15:20:49 - INFO - Session closed - _get_session - 73
14-11-2024 15:20:49 - ERROR - Wrong username or password - user_login - 39
14-11-2024 15:21:21 - INFO - Session closed - _get_session - 73
14-11-2024 15:21:21 - INFO - Login Successful. Welcome testuser - user_login - 33
14-11-2024 15:21:24 - WARNING - ====Cache miss==== - get - 93
14-11-2024 15:21:24 - INFO - Session closed - _get_session - 73
14-11-2024 15:21:24 - INFO - Redis connection closed - disconnect - 48
14-11-2024 15:21:27 - INFO - ====Cache hit==== - get - 96
14-11-2024 15:21:27 - INFO - Redis connection closed - disconnect - 48
14-11-2024 15:21:30 - INFO - ====Cache hit==== - get - 96
14-11-2024 15:21:30 - INFO - Redis connection closed - disconnect - 48
14-11-2024 15:21:38 - INFO - Connection closed - disconnect - 106
14-11-2024 15:21:38 - INFO - Logout Successful. Bye testuser - user_logout - 55
